name: Docker Image CI

on:
  workflow_dispatch:

env:
  IMAGE_NAME: openalex_search
  IMAGE_FULL_NAME: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Generate DATE_TAG
      id: date
      run: echo "DATE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build and Tag Docker Image
      run: |
        docker build . \
          -t ${{ env.IMAGE_FULL_NAME }}:latest \
          -t ${{ env.IMAGE_FULL_NAME }}:${{ env.DATE_TAG }}

    - name: Push the Docker Image
      run: |
        docker push ${{ env.IMAGE_FULL_NAME }}:latest
        docker push ${{ env.IMAGE_FULL_NAME }}:${{ env.DATE_TAG }}
